import turtle
turtle.color("blue")
turtle.penup()
turtle.goto(-250,0)
turtle.pendown()
turtle.circle(90)

turtle.color("black")
turtle.penup()
turtle.fd(250)
turtle.pendown()
turtle.circle(90)

turtle.color("red")
turtle.penup()
turtle.fd(250)
turtle.pendown()
turtle.circle(90)

turtle.color("yellow")
turtle.penup()
turtle.goto(-125,-100)
turtle.pendown()
turtle.circle(90)

turtle.color("green")
turtle.penup()
turtle.fd(250)
turtle.pendown()
turtle.circle(90)
turtle.mainloop()
